import pandas as pd
import MySQLdb

def main():
    '''This code finds unique module codes and their corresponding number
    of registered students. This file id dependent on the existence of codes.csv
    which is generated by timetable_parser.py. The file returns a csv file ready
    for importing into a mysql database'''
    
    print "Extracting Module Data..."
    # Read in CSV file to a pandas dataframe
    df = pd.read_csv("./data/Cleaned_Data/codes.csv", engine="python")
    
    #Drop unnecessary columns
    cols = [0,2,3]
    df.drop(df.columns[cols],axis=1,inplace=True)
    
    #Drop NaN rows
    df = df[pd.notnull(df['code'])]
    
    #Drop the careers row
    df = df[pd.notnull(df['students'])]
    
    #Drop duplicate codes
    df.drop_duplicates(['code'], inplace = True)
    df = df.reset_index(drop=True)
    
    #Change students type from float to integer
    df.students = df.students.astype(int)
    
    df.to_csv('./data/Cleaned_Data/modules.csv')
    print "Module Data extracted successfully."
    

if __name__ == "__main__":
    main()
